<?php

use MyTodo;

$eol = '<br />';
//$eol = PHP_EOL;

//echo 'Содержимое этого файла отдаётся по запросу аксиос.' . $eol;

$where = '';

$post =  json_decode(file_get_contents('php://input'), true);
switch ($post["flag"]) {
    case 0:
        $where = 'flag = 0';
        break;
    case 1:
        $where = 'flag = 1';
        break;
//    default:
//        $where = '';
}
$todos = $this->view->todos = MyTodo::find($where);

//print_r($post);

//echo 'Lines: ' . $todos->count() . $eol;

//foreach ($todos as $todo) {
//    echo $todo->id . ', ' . $todo->task . ', ' . $todo->dt . $eol;
//}


echo json_encode($todos); // . $eol;


// echo 'One record: ' . $todo1->id . ', ' . $todo1->task . ', ' . $todo1->dt . $eol;

//echo serialize($todos);




