<?php



?>

<p id="ab1"></p>

<p id="abzac2"></p>

<pre id="abzac"></pre>

<div id="todo-list" class="column is-half is-offset-one-quarter box content">
    <div class="panel">
        <p class="panel-heading">
            Список дел
        </p>
        <div class="panel-block">
            <input v-model="newTodo" class="input is-primary" type="text" placeholder="Что нужно сделать?"  @keyup="keyupTodo">
<!--            <button @click="addTodo" class="button is-primary">Добавить</button>-->
        </div>

        <div>
            <todo-item
                v-for="todo in todoList"
                v-bind:todo="todo"
                v-bind:arr="todoList"
            >
            </todo-item>
        </div>
    </div>
    <p> Количество дел: {{ this.todoList.length }}</p>
</div>

