<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <img src="/img/logo-earth.jpg" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item">
                В начало
            </a>

            <a class="navbar-item" href="/index/editor">
                Tiny MCS
            </a>

            <a class="navbar-item" href="/test_vue3.php">
                test_vue3
            </a>

            <a class="navbar-item" href="#">
                Файлы
            </a>

            <a class="navbar-item" href="/todo/index">
                Добрые дела
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    Ещё
                </a>
                <div class="navbar-dropdown">
                    <a class="navbar-item">
                        Контакты
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        О программе
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-link is-outlined" onclick="function f() {
                        document.location.href = '/users/login';   // В той же вкладке
//                         window.open('/users/form','_self',false);
//                         window.open('/users/form');  // В новой вкладке
                    }; f();">
                        Вход
                    </a>
                    <a class="button is-primary is-outlined" onclick="function f() {
                        document.location.href = '/users/form';   // В той же вкладке
//                         window.open('/users/form','_self',false);
//                         window.open('/users/form');  // В новой вкладке
                    }; f();">
                        Регистрация
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>