<?php

$post =  json_decode(file_get_contents('php://input'), true);

$dir = BASE_PATH . "/afm/" . $post["dirname"] . "/";

//if (!mkdir($dir, 0777, true)) {
if (!mkdir($dir)) {
    echo "Error";
} else {

    $fileinfo = [];

    $fileinfo['id'] = $post["id"];
    $fileinfo['name'] = $post["dirname"];
    $fileinfo['size'] = "0";
    $fileinfo['type'] = "dir";
    $fileinfo['checked'] = true;

    echo json_encode($fileinfo);
}


