<?php
//var_dump($_GET);
$fullname = BASE_PATH . "/../afm" . $_GET['dirname'] . '/' . $_GET['file'];
//echo $fullname;
//echo 'odsjlsjflks';
readfile($fullname);
//$fullname = BASE_PATH . "/../afm" . $_GET['filename'];
//echo $_GET['_url'] . '?dirname=' .  $_GET['dirname'] . '&files=' . $_GET['files'] . '&flag=' . $_GET['flag'];
//echo '<br>';

//if ($_GET['flag'] === '1') {
//    $ref = 'Location: ' . $_GET['_url'] . '?dirname=' .  $_GET['dirname'] . '&files=' . $_GET['files'] . '&flag=0';
//    echo $ref;
//    header ($ref);
//}
//loadFile($fullname);
//echo $fullname;

