<?php

//var_dump($_GET);
$fullname = BASE_PATH . "/../afm" . $_GET['dirname'] . '/' . $_GET['files'];
//$fullname = BASE_PATH . "/../afm" . $_GET['filename'];
//echo $_GET['_url'] . '?dirname=' .  $_GET['dirname'] . '&files=' . $_GET['files'] . '&flag=' . $_GET['flag'];
//echo '<br>';

//if ($_GET['flag'] === '1') {
//    $ref = 'Location: ' . $_GET['_url'] . '?dirname=' .  $_GET['dirname'] . '&files=' . $_GET['files'] . '&flag=0';
//    echo $ref;
//    header ($ref);
//}
loadFile($fullname);
//echo $fullname;

//header ('Location: ajax.php');


//echo $fullname;
//loadFile($fullname);

//$post =  json_decode(file_get_contents('php://input'), true);
//
//$dirname = $post["dirname"];
//$files = json_decode($post["files"]);
//
////echo $post["files"];
////echo count($files);
////echo $dirname . '<br>';
//
//$result = true;
//$fullname = BASE_PATH . "/../afm/newdir/2.txt";
//loadFile($fullname);


//$count = count($files);
//for ($i = 0; $i < $count; $i++) {
//    $fullname = BASE_PATH . "/../afm" . $dirname . '/' . $files[$i];
//    if (is_dir($fullname)) {
////        echo $fullname . ' dir<br>';
////        $result = loadDir($fullname) && $result;
//    } else {
////        echo $fullname . ' file<br>';
//        loadFile($fullname);
//    }
//
//}

function loadFile($file)
{
//    echo $file;
//    echo '---' . basename($file);
    //return;
    //http://bc.eopa.ru/storage/load?filename=Pagination.jpg&token=7994c058203cda63aa2bbf3bbc0df7fedcaa1c1b2e05c94a4076e97099cd.xbz
//    if (!file_exists($file)) {
//        echo 'Fайл <b>' . $filename . '</b> не существует.';
//        return;
//    }
//
    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename=11' . basename($file));
    header('Content-Transfer-Encoding: binary');
    header('Expires: 0');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');

    // читаем файл и отправляем его пользователю
    readfile($file);

}
