<?php

    $dir = BASE_PATH . "/public/";
    $fileinfo = [];
    $files = [];
    $index = 1;

    // Открыть известный каталог и начать считывать его содержимое
    if (is_dir($dir)) {
        //использовать scandir для сортировки
//        if ($dh = opendir($dir)) {
        if ($dh = scandir($dir, 0)) {
//            while (($file = readdir($dh)) !== false) {
            $count = count($dh);
            for ($i = 0; $i < $count; $i++) {
                $file = $dh[$i];
//                echo "файл: $file : ";
//                echo $type = filetype($dir . $file);
//                echo $size === 'file' ? filesize($dir . $file) : "";
//                echo "<br>\n";

//                $fileinfo['index'] = $index;
                $fileinfo['index'] = $i;
                $fileinfo['name'] = $file;

//                $size = ($type === 'file') ? filesize($dir . $file) : "0";
                $size = filesize($dir . $file);
                $fileinfo['size'] = $size;

                $type = filetype($dir . $file);
                if ($type === 'file') {
                    $type = pathinfo( $file, PATHINFO_EXTENSION );
                }

                $fileinfo['type'] = $type;

                $fileinfo['checked'] = false;

                $files[$i] = $fileinfo;
            }
            closedir($dh);
        }
    }

echo json_encode($files);