<?php

    $post =  json_decode(file_get_contents('php://input'), true);

//    $dir = BASE_PATH . "/public/" . $post["dirname"] . "/";
    $dir = BASE_PATH . "/../afm/" . $post["dirname"] . "/";
    $fileinfo = [];
    $files = [];

    // Открыть известный каталог и начать считывать его содержимое
    if (is_dir($dir)) {
        //использовать scandir для сортировки
//        if ($dh = opendir($dir)) {
        if ($dh = scandir($dir, 0)) {
//            while (($file = readdir($dh)) !== false) {
            $count = count($dh);
            // Здесь я убрал первый элемент . (точку)
            // для этого начал цикл со второго элемента (с индекса 1)
            // но для JavaScript нумерую массив с 0 (с нуля)
            // потому что иначе он не воспримет это не как массив, а как объект, а это уже совсем другие методы работы.
            for ($i = 1; $i < $count; $i++) {
                $file = $dh[$i];

                $fileinfo['id'] = $i - 1;
                $fileinfo['name'] = $file;
                
                $fileinfo['size'] = filesize($dir . $file);;

                $type = filetype($dir . $file);
                if ($type === 'dir') {
                    $dir2 = $dir . $file . '/';
                    if (is_dir($dir2)) {
                        if ($dh2 = scandir($dir2, 0)) {
                            $fileinfo['size'] =  count($dh2) - 2;
                        }
                    }
                } else { // if ($type === 'file') {
                    $type = pathinfo( $file, PATHINFO_EXTENSION );
                }

                $fileinfo['type'] =  $type;
                $fileinfo['checked'] = false;

                $files[$i - 1] = $fileinfo;
            }
            closedir($dh);
        }
    }

echo json_encode($files);