<?php

use Phalcon\Forms\Form;
use Phalcon\Forms\Element\Text;
use Phalcon\Forms\Element\Select;

$form = new Form();

$form->add(
    new Text(
        'nameLast',
        [
            'maxlength'   => 30,
            'placeholder' => 'Last Name',
        ]
    )
);

$form->add(
    new Text(
        'nameFirst'
    )
);

$form->add(
    new Select(
        'phoneType',
        [
            1 => 'Домашний',
            2 => 'Рабочий',
            3 => 'Мобильный',
        ]
    )
);


?>

<div class="block">

<h1 class="h1">
    Регистрация
</h1>

<form method='post'>

    <p>
        <label>
            Логин
        </label>

        <?php echo $form->render('nameLast'); ?>
    </p>

    <p>
        <label>
            Имя
        </label>

        <?php
        echo $form->render(
            'nameFirst',
            [
                'maxlength'   => 30,
                'placeholder' => 'First Name',
            ]
        ); ?>
    </p>

    <p>
        <label>
            Тип телефона
        </label>

        <?php echo $form->render('phoneType'); ?>
    </p>

    <p>
        <input type='submit' value='Регистрация' />
    </p>


</form>

</div>