<?php

use Phalcon\Forms\Form;
use Phalcon\Forms\Element\Text;
use Phalcon\Forms\Element\Select;

$form = new Form();

$form->add(
    new Text(
        'nameLast',
        [
            'maxlength'   => 30,
            'placeholder' => 'Last Name',
        ]
    )
);


?>

<div class="block">

    <h1 class="h1">
        Вход
    </h1>

    <form method='post'>

        <p>
            <label>
                Last Name
            </label>

            <?php echo $form->render('nameLast'); ?>
        </p>


        <p>
            <input type='submit' value='Вход' />
        </p>


    </form>

</div>