<div>
    <form action="/index/save" method='post' >
        <span>Редактор</span>
        <textarea name="text">
            Welcome to TinyMCE!
        </textarea>
        <button>Save</button>
    </form>
</div>

<script src="https://cdn.tiny.cloud/1/by218y9v8w5scrhnsto0dyv7uk6htpw5unp6zo54rezrg8br/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: 'textarea',
//          plugins: 'a11ychecker advcode casechange formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
          plugins: 'mediaembed',
//        toolbar: 'a11ycheck addcomment showcomments casechange checklist code formatpainter pageembed permanentpen table',
//        toolbar: '',
//        toolbar_mode: 'floating',
//        tinycomments_mode: 'embedded',
//        tinycomments_author: 'Author name',
    });
</script>
